export const AUTH_START = "AUTH_START";
export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";

export const LOADING_TEAMS_START = "LOADING_TEAMS_START";
export const LOADING_TEAM_SUCCESS = "LOADING_TEAM_SUCCESS";
export const LOADING_TEAMS_SUCCESS = "LOADING_TEAMS_SUCCESS";
export const LOADING_TEAMS_FAIL = "LOADING_TEAMS_FAIL";
export const ADD_TEAM = "ADD_TEAM";
export const SET_CURRENT_TEAM = "SET_CURRENT_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const LOGOUT_TEAM = "LOGOUT_TEAM";

export const LOADING_LEADS_START = "LOADING_LEADS_START";
export const LOADING_LEADS_SUCCESS = "LOADING_LEADS_SUCCESS";
export const LOADING_LEADS_FAIL = "LOADING_LEADS_FAIL";
export const ADD_LEAD = "ADD_LEAD";
export const DELETE_LEAD = "DELETE_LEAD";
export const EDIT_LEAD = "EDIT_LEAD";

export const LOADING_CLIENTS_START = "LOADING_CLIENTS_START";
export const LOADING_CLIENTS_SUCCESS = "LOADING_CLIENTS_SUCCESS";
export const LOADING_CLIENTS_FAIL = "LOADING_CLIENTS_FAIL";
export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
