export const AUTH_START = "AUTH_START";
export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";

export const LOADING_TEAMS_START = "LOADING_TEAMS_START";
export const LOADING_TEAM_SUCCESS = "LOADING_TEAM_SUCCESS";
export const LOADING_TEAMS_SUCCESS = "LOADING_TEAMS_SUCCESS";
export const LOADING_TEAMS_FAIL = "LOADING_TEAMS_FAIL";
export const ADD_TEAM = "ADD_TEAM";
export const SET_CURRENT_TEAM = "SET_CURRENT_TEAM";
export const LOGOUT_TEAM = "LOGOUT_TEAM";
